version: '3.9'

services:
  api:
    build: .
    container_name: dt365-backend
    restart: always
    env_file:
      - .env.production
    expose:
      - '3001'
    ports:
      - '3001:3001'
    networks:
      - dt365-network

  nginx:
    image: nginx:alpine
    container_name: dt365-nginx
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
    networks:
      - dt365-network

networks:
  dt365-network:
    driver: bridge
